### ISSUE TITLE
تنوین و همزه

### ISSUE THREAD

**Issue by 5j9** [jadijadi/justforfun#5]
من می‌خواستم در تعدادی از فایل‌ها تنوین‌ها رو اصلاح کنم، ولی گفتم شاید کلاً با استفاده از اون‌ها موافق نباشید.

به هر حال اگر موافق بودید من حاضرم تعدادی از این موارد رو اصلاح کنم. تغییرات جزئی‌ای مثل: تبدیل «لطفا» به «لطفاً» یا «موسسه» به «مؤسسه».

**Comment by jadijadi** [comment]
سلام. چقدر خوب که پرسیدی. راستش من در اینترنت از همزه و تنوین و این تیپ
چیزها استفاده نمی کنم چون به نظرم هم خوندن رو سخت تر می کنه و هم سرچ رو.
ممنون از لطف و وقتی که گذاشتی و می خواستی بذاری و ممنون از شیوه صحیح مطرح
کردن مساله (:

جادی

2015-03-25 12:51 GMT+04:30 irdb <notifications@github.com>:
